version: '3.8'

services:
  # Backend API service (without Redis dependency)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: legal-analyzer-backend-no-redis
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - MAX_CONCURRENT_ANALYSES=5
      - CACHE_RETENTION_HOURS=24
      - CLEANUP_INTERVAL_HOURS=1
      - RATE_LIMIT_REQUESTS_PER_MINUTE=100
      # Redis disabled - using in-memory storage
      # - REDIS_URL=redis://redis:6379/0
      # - CELERY_BROKER_URL=redis://redis:6379/0
      # - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - backend_logs:/app/logs
      - backend_exports:/app/exports
      - backend_temp:/app/temp_uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend web application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: legal-analyzer-frontend-no-redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  backend_logs:
    driver: local
  backend_exports:
    driver: local
  backend_temp:
    driver: local
